--- #YAML:1.0
name:                Audio-M4P
version:             0.35
abstract:            Perl M4P/MP4/M4a video and audio meia file tools, now (alpha) strips personal ID information from Apple .m4a files
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Crypt::Rijndael:               0
    Digest::MD5:                   0
    Test::More:                    0
    Tree::Simple:                  0
    Tree::Simple::View::HTML:      0
    Tree::Simple::Visitor:         0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - William Hererra (whererra@skylightview.com)
