---
abstract: Perl M4P/MP4/M4a video and audio media file tools
author:
  - William Hererra (whererra@skylightview.com)
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Audio-M4P
no_index:
  directory:
    - t
    - inc
requires:
  Crypt::Rijndael: 0
  Digest::MD5: 0
  Scalar::Util: 0
  Test::More: 0
  Tree::Simple: 0
  Tree::Simple::View::HTML: 0
  Tree::Simple::Visitor: 0
version: 0.57
